### ISSUE TITLE
All declarations of 'Service' must have identical type parameters.

### ISSUE THREAD

**Issue by michaelbenoit** [feathersjs-ecosystem/feathers-chat-angular#4] opened 2017-10-08 10:16 UTC
I'm not able to run the example.
I get the following error:
```
ERROR in /Users/michaelbenoit/Projects/javascript/feathers-chat-angular/node_modules/feathers-reactive/index.d.ts (26,13): All declarations of 'Service' must have identical type parameters.
ERROR in /Users/michaelbenoit/Projects/javascript/feathers-chat-angular/node_modules/feathers-hooks/index.d.ts (8,13): All declarations of 'Service' must have identical type parameters.
```

**Comment by j2L4e** [comment] 2017-10-08 11:04
I can't reproduce this.

```
$ git clone https://github.com/feathersjs/feathers-chat-angular.git
$ cd feathers-chat-angular
$ npm install
$ ng s
```
```webpack: Compiled successfully.```

There was a typings inconsistency of hooks, reactive and core for a quite short period which has been resolved though. Please delete node_modules (and yarn.lock if you use yarn) and reinstall.


Edit: __Scratch that! Maybe I should have deleted yarn.lock myself. Reproduced.__

Edit2: problem is that `feathers-client` is pinned to `feathers` 2.2.0.

Edit3: Workaround added by adding `feathers: ^2.2.2` to package.json. In general needs to be fixed in `feathers-client`

**Closed as completed** 2017-10-08 11:36 UTC

**Comment by michaelbenoit** [comment] 2017-10-08 12:29
Yes you're right I was able to get it running. Mainly the package-lock file was the problem!
Many thanks for your support :-)
